Keep track of when builds are ready. CLoses #13
rogerluan/app-store-connect-notifier pull request #160
Opened 2021-11-27 07:53 UTC by johnf

Keeps track of the last X builds and sends a message as they appear and with their status

2021-12-03 19:13 UTC, rogerluan requested changes

2021-12-03 19:13 UTC, rogerluan commented on src/fetch_app_status.rb
> +      "status" => build.processing_state,
Can we switch to more modern syntax?

```suggestion
      version: build.version,
      uploaded_data: build.uploaded_date,
      status: build.processing_state,
```

2021-12-03 19:13 UTC, rogerluan commented on src/poll-itc.js
> +    // Store latest build info in database
You probably meant to put this in the line above? haha
```suggestion
```

2021-12-03 19:13 UTC, rogerluan commented on src/poll-itc.js
> +        db.set(buildInfoKey, newBuildInfo)
```suggestion
        // Store latest build info in database
        db.set(buildInfoKey, newBuildInfo)
```

2021-12-03 19:14 UTC, rogerluan approved these changes
Thanks A LOT for this PR!! Your code LGTM. Looking forward to using this feature 🌟  Nicely done!

2021-12-03 19:15 UTC, merged

2021-12-04 00:46 UTC, johnf commented
All good, thanks for merging!
Let me know when you do the next release if the docker workflow has any issues

2021-12-04 02:37 UTC, rogerluan commented
I just published a release https://github.com/rogerluan/app-store-connect-notifier/releases/tag/v2.2.0 💪 I'll let you know if there're any issues 😁

2021-12-04 03:03 UTC, johnf commented
You'll need to add two secrets , your docker hub username and password.
![image](https://user-images.githubusercontent.com/42590/144694628-6c2bc786-7f8f-4664-a41d-43dbedb66598.png)