Clean up the spaceship logs
rogerluan/app-store-connect-notifier pull request #264
Opened 2023-03-03 23:35 UTC by johnf

I discovered I had 100GB of logs in /tmp
Unfortunately spaceship doesn't have a nice way of turning this off from what I found https://github.com/fastlane/fastlane/issues/12854

2023-03-07 13:04 UTC, rogerluan requested changes
Just wondering: what OS are you using, is it macOS or linux?
I've been running this script on my local machine for many months now, almost non-stop (only pause when I need to restart the machine to apply OS updates), and I couldn't find logs older than 7 days (as your script is configured). Maybe I rebooted <7 days ago (can't remember) which would then clean the tmp dir, but I was just wondering if this behavior is different if running on Linux for instance

Thanks for flagging this and proposing a fix, btw 💪 great find!
For the past few days, my computer collected 2GB worth of logs 😓

2023-03-07 13:04 UTC, rogerluan commented on src/poll-itc.js
> +    exec("find /tmp -maxdepth 1 -name 'spaceship*.log' -mtime +7 -delete")
Did you mean this instead?

```suggestion
    exec("find /tmp/ -maxdepth 1 -name 'spaceship*.log' -mtime +7 -delete")
```

Without the trailing `/`, it wouldn't find anything

2023-03-07 20:18 UTC, johnf commented
> Just wondering: what OS are you using, is it macOS or linux? I've been running this script on my local machine for many months now, almost non-stop (only pause when I need to restart the machine to apply OS updates), and I couldn't find logs older than 7 days (as your script is configured). Maybe I rebooted <7 days ago (can't remember) which would then clean the tmp dir, but I was just wondering if this behavior is different if running on Linux for instance
> 
> Thanks for flagging this and proposing a fix, btw muscle great find! For the past few days, my computer collected 2GB worth of logs sweat

I'm running it in the docker container on a server, and it was using my published docker image which I hadn't update in forever so it had been running for months.

On linux it works with and without the / maybe find is slightly different on MacOS? I'll update to add the /

2023-03-08 16:50 UTC, rogerluan commented
>On linux it works with and without the / maybe find is slightly different on MacOS? I'll update to add the /

That's what I thought heh yeah macOS is weird with some of the "native" commands, like `awk`, `sed`, maybe `find` too 😬 classic 🍏😅

2023-03-08 16:51 UTC, rogerluan approved these changes
Thanks for this 🚀 great improvement!

2023-03-08 16:51 UTC, merged